import { Template } from "@repo/shared";

export const templateData: Template[] = [
  {
    _id: "1",
    name: "SaaS Starter",
    slug: "saas-starter",
    description:
      "Production-ready SaaS starter with authentication and dashboard.",
    stack: ["React", "Next.js", "TypeScript", "Tailwind", "Node.js"],
    tags: ["saas", "auth", "dashboard", "starter"],
    features: [
      "Authentication preconfigured",
      "JWT-based access control",
      "Responsive dashboard UI",
      "Protected routes setup",
      "API-ready backend",
    ],
    repoUrl: "#",
    version: "1.0.0",
    codeUrl: "#",
    liveUrl: "#",
    folderStructure: "src/\n  components/\n  pages/\n  api/\n  utils/",
    withoutLogin: false,
    isPro: false,
    creditCost: 0,
    isPublished: true,
    isFeatured: true,
    isSponsored: true,
    sponsoredBy: {
      name: "Next.js",
      url: "https://nextjs.org",
      logo: "https://nextjs.org/favicon.ico",
    },
    isDeleted: false,
    isRepoTemplate: true,
    installer: {
      name: "devkit",
      dependencies: "react,next",
      devDependencies: "typescript",
      installCommand: "devkit add saas-starter",
      addDependenciesCommand: "",
      addDevDependenciesCommand: "",
    },
    imageUrl: "/img/1.png",
    videoUrl: "",
    views: 1200,
    copies: 300,
    downloads: 800,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "2",
    name: "Ecommerce UI",
    slug: "ecommerce-ui",
    description: "Modern ecommerce frontend with cart and checkout.",
    stack: ["React", "Vite", "TypeScript", "Tailwind", "Zustand"],
    tags: ["ecommerce", "ui", "cart", "shop"],
    features: [
      "Product listing UI",
      "Cart management system",
      "Checkout flow",
      "Responsive design",
      "Optimized performance",
    ],
    repoUrl: "#",
    version: "1.0.0",
    codeUrl: "#",
    liveUrl: "#",
    folderStructure: "src/\n  components/\n  pages/\n  store/\n  hooks/",
    withoutLogin: true,
    isPro: false,
    creditCost: 0,
    isPublished: true,
    isFeatured: false,
    isSponsored: false,
    isDeleted: false,
    isRepoTemplate: true,
    installer: {
      name: "devkit",
      dependencies: "react,zustand",
      devDependencies: "typescript",
      installCommand: "devkit add ecommerce-ui",
      addDependenciesCommand: "",
      addDevDependenciesCommand: "",
    },
    imageUrl: "/img/2.png",
    videoUrl: "",
    views: 900,
    copies: 200,
    downloads: 600,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "3",
    name: "Blog Platform",
    slug: "blog-platform",
    description: "Full blog platform with markdown support.",
    stack: ["Next.js", "MongoDB", "TypeScript", "Tailwind", "Express"],
    tags: ["blog", "cms", "markdown", "content"],
    features: [
      "Markdown editor",
      "SEO optimized pages",
      "Auth system",
      "Content management",
      "Comment system",
    ],
    repoUrl: "#",
    version: "1.2.0",
    codeUrl: "#",
    liveUrl: "#",
    folderStructure: "server/\n  models/\n  routes/\nclient/\n  pages/",
    withoutLogin: false,
    isPro: true,
    creditCost: 5,
    isPublished: true,
    isFeatured: true,
    isSponsored: false,
    isDeleted: false,
    isRepoTemplate: true,
    installer: {
      name: "devkit",
      dependencies: "next,mongodb",
      devDependencies: "typescript",
      installCommand: "devkit add blog-platform",
      addDependenciesCommand: "",
      addDevDependenciesCommand: "",
    },
    imageUrl: "/img/3.png",
    videoUrl: "",
    views: 2000,
    copies: 500,
    downloads: 1500,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "4",
    name: "Kanban Board",
    slug: "kanban-board",
    description: "Task management board with drag and drop.",
    stack: ["React", "TypeScript", "Zustand", "Tailwind", "Node.js"],
    tags: ["kanban", "task", "productivity", "drag"],
    features: [
      "Drag and drop tasks",
      "Board management",
      "Member roles",
      "Task logs",
      "Realtime updates",
    ],
    repoUrl: "#",
    version: "1.1.0",
    codeUrl: "#",
    liveUrl: "#",
    folderStructure: "src/\n  boards/\n  tasks/\n  store/",
    withoutLogin: false,
    isPro: true,
    creditCost: 8,
    isPublished: true,
    isFeatured: false,
    isSponsored: true,
    sponsoredBy: {
      name: "Google",
      url: "https://google.com",
      logo: "https://google.com/favicon.ico",
    },
    isDeleted: false,
    isRepoTemplate: true,
    installer: {
      name: "devkit",
      dependencies: "react,zustand",
      devDependencies: "typescript",
      installCommand: "devkit add kanban-board",
      addDependenciesCommand: "",
      addDevDependenciesCommand: "",
    },
    imageUrl: "/img/4.png",
    videoUrl: "",
    views: 1500,
    copies: 400,
    downloads: 1100,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "5",
    name: "Portfolio Site",
    slug: "portfolio-site",
    description: "Minimal portfolio with animations.",
    stack: ["React", "Vite", "Tailwind", "Framer Motion", "TypeScript"],
    tags: ["portfolio", "personal", "ui", "animation"],
    features: [
      "Animated UI",
      "Project showcase",
      "Responsive layout",
      "Dark mode",
      "Fast performance",
    ],
    repoUrl: "#",
    version: "1.0.0",
    codeUrl: "#",
    liveUrl: "#",
    folderStructure: "src/\n  components/\n  sections/",
    withoutLogin: true,
    isPro: false,
    creditCost: 0,
    isPublished: true,
    isFeatured: true,
    isSponsored: false,
    isDeleted: false,
    isRepoTemplate: true,
    installer: {
      name: "devkit",
      dependencies: "react,framer-motion",
      devDependencies: "typescript",
      installCommand: "devkit add portfolio-site",
      addDependenciesCommand: "",
      addDevDependenciesCommand: "",
    },
    imageUrl: "/img/5.png",
    videoUrl: "",
    views: 800,
    copies: 150,
    downloads: 500,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "6",
    name: "Auth System",
    slug: "auth-system",
    description: "Complete auth system with OTP and JWT.",
    stack: ["Node.js", "Express", "MongoDB", "TypeScript", "JWT"],
    tags: ["auth", "backend", "security", "otp"],
    features: [
      "Email OTP verification",
      "JWT authentication",
      "Password reset flow",
      "Secure routes",
      "Token refresh",
    ],
    repoUrl: "#",
    version: "1.0.0",
    codeUrl: "#",
    liveUrl: "#",
    folderStructure: "server/\n  controllers/\n  routes/",
    withoutLogin: false,
    isPro: true,
    creditCost: 4,
    isPublished: true,
    isFeatured: false,
    isSponsored: false,
    isDeleted: false,
    isRepoTemplate: true,
    installer: {
      name: "devkit",
      dependencies: "express,mongodb",
      devDependencies: "typescript",
      installCommand: "devkit add auth-system",
      addDependenciesCommand: "",
      addDevDependenciesCommand: "",
    },
    imageUrl: "/img/6.png",
    videoUrl: "",
    views: 1100,
    copies: 250,
    downloads: 700,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "7",
    name: "Admin Dashboard",
    slug: "admin-dashboard",
    description: "Powerful admin panel with charts.",
    stack: ["React", "Chart.js", "Tailwind", "TypeScript", "Node.js"],
    tags: ["admin", "dashboard", "analytics", "charts"],
    features: [
      "Analytics charts",
      "User management",
      "Role permissions",
      "Data tables",
      "Export data",
    ],
    repoUrl: "#",
    version: "1.0.0",
    codeUrl: "#",
    liveUrl: "#",
    folderStructure: "src/\n  dashboard/\n  charts/",
    withoutLogin: false,
    isPro: true,
    creditCost: 6,
    isPublished: true,
    isFeatured: true,
    isSponsored: true,
    sponsoredBy: {
      name: "OpenAI",
      url: "https://openai.com",
      logo: "https://openai.com/favicon.ico",
    },
    isDeleted: false,
    isRepoTemplate: true,
    installer: {
      name: "devkit",
      dependencies: "react,chart.js",
      devDependencies: "typescript",
      installCommand: "devkit add admin-dashboard",
      addDependenciesCommand: "",
      addDevDependenciesCommand: "",
    },
    imageUrl: "/img/7.png",
    videoUrl: "",
    views: 1800,
    copies: 600,
    downloads: 1400,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "8",
    name: "Landing Page",
    slug: "landing-page",
    description: "High-converting modern landing page.",
    stack: ["React", "Tailwind", "TypeScript", "Framer Motion", "Vite"],
    tags: ["landing", "marketing", "ui", "hero"],
    features: [
      "Hero sections",
      "CTA optimized",
      "Animations",
      "Responsive design",
      "SEO ready",
    ],
    repoUrl: "#",
    version: "1.0.0",
    codeUrl: "#",
    liveUrl: "#",
    folderStructure: "src/\n  sections/\n  components/",
    withoutLogin: true,
    isPro: false,
    creditCost: 0,
    isPublished: true,
    isFeatured: true,
    isSponsored: false,
    isDeleted: false,
    isRepoTemplate: true,
    installer: {
      name: "devkit",
      dependencies: "react",
      devDependencies: "typescript",
      installCommand: "devkit add landing-page",
      addDependenciesCommand: "",
      addDevDependenciesCommand: "",
    },
    imageUrl: "/img/8.png",
    videoUrl: "",
    views: 1300,
    copies: 350,
    downloads: 900,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "9",
    name: "Chat App",
    slug: "chat-app",
    description: "Realtime chat application with sockets.",
    stack: ["React", "Node.js", "Socket.io", "TypeScript", "MongoDB"],
    tags: ["chat", "realtime", "socket", "messaging"],
    features: [
      "Realtime messaging",
      "Typing indicators",
      "Online status",
      "Message history",
      "Group chats",
    ],
    repoUrl: "#",
    version: "1.0.0",
    codeUrl: "#",
    liveUrl: "#",
    folderStructure: "server/\n  socket/\nclient/",
    withoutLogin: false,
    isPro: true,
    creditCost: 7,
    isPublished: true,
    isFeatured: false,
    isSponsored: false,
    isDeleted: false,
    isRepoTemplate: true,
    installer: {
      name: "devkit",
      dependencies: "socket.io",
      devDependencies: "typescript",
      installCommand: "devkit add chat-app",
      addDependenciesCommand: "",
      addDevDependenciesCommand: "",
    },
    imageUrl: "/img/9.png",
    videoUrl: "",
    views: 1600,
    copies: 500,
    downloads: 1200,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  {
    _id: "10",
    name: "AI Dashboard",
    slug: "ai-dashboard",
    description: "AI-powered analytics dashboard.",
    stack: ["React", "Next.js", "OpenAI", "TypeScript", "Tailwind"],
    tags: ["ai", "dashboard", "analytics", "openai"],
    features: [
      "AI insights",
      "Data visualization",
      "API integration",
      "User dashboards",
      "Realtime updates",
    ],
    repoUrl: "#",
    version: "1.0.0",
    codeUrl: "#",
    liveUrl: "#",
    folderStructure: "src/\n  ai/\n  charts/",
    withoutLogin: false,
    isPro: true,
    creditCost: 10,
    isPublished: true,
    isFeatured: true,
    isSponsored: false,
    isDeleted: false,
    isRepoTemplate: true,
    installer: {
      name: "devkit",
      dependencies: "openai,next",
      devDependencies: "typescript",
      installCommand: "devkit add ai-dashboard",
      addDependenciesCommand: "",
      addDevDependenciesCommand: "",
    },
    imageUrl: "/img/10.png",
    videoUrl: "",
    views: 2200,
    copies: 700,
    downloads: 1800,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
