import { Template } from "@repo/shared";

export const templateData: Template[] = [
  {
    _id: "tpl_004",
    name: "Vue E-Commerce Starter",
    slug: "vue-ecommerce-starter",
    description:
      "A modern e-commerce boilerplate built with Vue.js, Pinia, and Stripe integration.",
    stack: ["Vue.js", "Pinia", "Stripe", "Tailwind CSS"],
    tags: ["ecommerce", "frontend", "payments"],
    repoUrl: "https://github.com/example/vue-ecommerce-starter",
    version: "1.0.3",
    isPro: true,
    creditCost: 20,
    isPublished: true,
    isFeatured: true,
    isSponsored: false,
    isDeleted: false,
    sponsoredBy: { name: "", url: "", logo: "" },
    isRepoTemplate: true,
    installer: {
      name: "npm",
      dependencies: "vue pinia stripe tailwindcss",
      devDependencies: "eslint prettier vite",
      installCommand: "npm install",
      addDependenciesCommand: "npm install <package>",
      addDevDependenciesCommand: "npm install -D <package>",
    },
    folderStructureImage: "https://example.com/images/vue-ecommerce.png",
    videoUrl: "https://www.youtube.com/watch?v=vuecommerce123",
    views: 9200,
    copies: 310,
    downloads: 780,
    createdAt: new Date("2024-01-10T14:00:00"),
    updatedAt: new Date("2024-01-10T14:00:00"),
  },
  {
    _id: "tpl_005",
    name: "Django Blog CMS",
    slug: "django-blog-cms",
    description:
      "A full-featured blog CMS built with Django, PostgreSQL, and Bootstrap.",
    stack: ["Django", "PostgreSQL", "Bootstrap"],
    tags: ["cms", "blog", "backend"],
    repoUrl: "https://github.com/example/django-blog-cms",
    version: "3.1.0",
    isPro: false,
    creditCost: 1,
    isPublished: true,
    isFeatured: false,
    isSponsored: true,
    isDeleted: false,
    sponsoredBy: {
      name: "DigitalOcean",
      url: "https://digitalocean.com",
      logo: "https://do.co/logo.png",
    },
    isRepoTemplate: true,
    installer: {
      name: "pip",
      dependencies: "django psycopg2 gunicorn",
      devDependencies: "pytest black",
      installCommand: "pip install -r requirements.txt",
      addDependenciesCommand: "pip install <package>",
      addDevDependenciesCommand: "pip install <package> --dev",
    },
    folderStructureImage: "https://example.com/images/django-blog.png",
    videoUrl: "https://www.youtube.com/watch?v=djangoBlog123",
    views: 13400,
    copies: 420,
    downloads: 1100,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "tpl_006",
    name: "Angular Admin Dashboard",
    slug: "angular-admin-dashboard",
    description:
      "Enterprise-ready admin dashboard template with Angular and Material UI.",
    stack: ["Angular", "RxJS", "Material UI"],
    tags: ["dashboard", "admin", "frontend"],
    repoUrl: "https://github.com/example/angular-admin-dashboard",
    version: "2.4.2",
    isPro: true,
    creditCost: 30,
    isPublished: true,
    isFeatured: true,
    isSponsored: false,
    isDeleted: false,
    sponsoredBy: { name: "", url: "", logo: "" },
    isRepoTemplate: true,
    installer: {
      name: "npm",
      dependencies: "angular rxjs @angular/material",
      devDependencies: "eslint prettier jasmine karma",
      installCommand: "npm install",
      addDependenciesCommand: "npm install <package>",
      addDevDependenciesCommand: "npm install -D <package>",
    },
    folderStructureImage: "https://example.com/images/angular-dashboard.png",
    videoUrl: "https://www.youtube.com/watch?v=angularDash123",
    views: 15800,
    copies: 500,
    downloads: 1400,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "tpl_007",
    name: "Flask Machine Learning API",
    slug: "flask-ml-api",
    description:
      "Deploy ML models with Flask and scikit-learn, ready for production.",
    stack: ["Flask", "scikit-learn", "Docker"],
    tags: ["ml", "api", "backend"],
    repoUrl: "https://github.com/example/flask-ml-api",
    version: "0.5.0",
    isPro: false,
    creditCost: 1,
    isPublished: true,
    isFeatured: false,
    isSponsored: false,
    isDeleted: false,
    sponsoredBy: { name: "", url: "", logo: "" },
    isRepoTemplate: true,
    installer: {
      name: "pip",
      dependencies: "flask scikit-learn numpy pandas",
      devDependencies: "pytest black",
      installCommand: "pip install -r requirements.txt",
      addDependenciesCommand: "pip install <package>",
      addDevDependenciesCommand: "pip install <package> --dev",
    },
    folderStructureImage: "https://example.com/images/flask-ml.png",
    videoUrl: "https://www.youtube.com/watch?v=flaskML123",
    views: 7200,
    copies: 180,
    downloads: 560,
    createdAt: new Date("2023-12-01T10:00:00"),
    updatedAt: new Date("2025-02-15T16:30:00"),
  },
  {
    _id: "tpl_008",
    name: "React Native Fitness App",
    slug: "react-native-fitness-app",
    description:
      "Cross-platform fitness tracking app built with React Native and Firebase.",
    stack: ["React Native", "Firebase", "Expo"],
    tags: ["mobile", "fitness", "cross-platform"],
    repoUrl: "https://github.com/example/react-native-fitness-app",
    version: "1.1.0",
    isPro: true,
    creditCost: 25,
    isPublished: true,
    isFeatured: true,
    isSponsored: true,
    isDeleted: false,
    sponsoredBy: {
      name: "Firebase",
      url: "https://firebase.google.com",
      logo: "https://firebase.google.com/logo.png",
    },
    isRepoTemplate: true,
    installer: {
      name: "npm",
      dependencies: "react-native expo firebase",
      devDependencies: "eslint prettier jest",
      installCommand: "npm install",
      addDependenciesCommand: "npm install <package>",
      addDevDependenciesCommand: "npm install -D <package>",
    },
    folderStructureImage: "https://example.com/images/react-native-fitness.png",
    videoUrl: "https://www.youtube.com/watch?v=rnFitness123",
    views: 11000,
    copies: 390,
    downloads: 950,
    createdAt: new Date("2024-03-15T09:30:00"),
    updatedAt: new Date("2025-04-05T15:45:00"),
  },
  {
    _id: "21",
    name: "Django Blog CMS",
    slug: "django-blog-cms",
    description:
      "Full-featured blog CMS with Django, PostgreSQL, and Bootstrap.",
    stack: ["django", "postgresql", "bootstrap"],
    tags: ["cms", "blog", "backend"],
    repoUrl: "https://github.com/demo/django-blog",
    version: "3.1.0",

    isPro: false,
    creditCost: 0,

    isPublished: true,
    isFeatured: false,
    isSponsored: true,
    isDeleted: false,
    sponsoredBy: {
      name: "DigitalOcean",
      url: "https://digitalocean.com",
      logo: "/logos/do.svg",
    },

    isRepoTemplate: true,
    installer: {
      name: "pip",
      dependencies: "django psycopg2 gunicorn",
      devDependencies: "pytest black",
      installCommand: "pip install -r requirements.txt",
      addDependenciesCommand: "pip install <package>",
      addDevDependenciesCommand: "pip install <package> --dev",
    },

    folderStructureImage: "/templates/django-blog.png",
    videoUrl: "https://youtube.com/demo21",

    views: 13400,
    copies: 420,
    downloads: 1100,

    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "22",
    name: "Angular Admin Dashboard",
    slug: "angular-admin-dashboard",
    description:
      "Enterprise-ready admin dashboard with Angular and Material UI.",
    stack: ["angular", "rxjs", "material-ui"],
    tags: ["dashboard", "admin", "frontend"],
    repoUrl: "https://github.com/demo/angular-dashboard",
    version: "2.4.2",

    isPro: true,
    creditCost: 6,

    isPublished: true,
    isFeatured: true,
    isSponsored: false,
    isDeleted: false,
    sponsoredBy: { name: "", url: "", logo: "" },

    isRepoTemplate: true,
    installer: {
      name: "npm",
      dependencies: "angular rxjs @angular/material",
      devDependencies: "eslint prettier jasmine karma",
      installCommand: "npm install",
      addDependenciesCommand: "npm install <package>",
      addDevDependenciesCommand: "npm install -D <package>",
    },

    folderStructureImage: "/templates/angular-dashboard.png",
    videoUrl: "https://youtube.com/demo22",

    views: 15800,
    copies: 500,
    downloads: 1400,

    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "23",
    name: "Flask ML API",
    slug: "flask-ml-api",
    description:
      "Deploy ML models with Flask and scikit-learn, ready for production.",
    stack: ["flask", "scikit-learn", "docker"],
    tags: ["ml", "api", "backend"],
    repoUrl: "https://github.com/demo/flask-ml",
    version: "0.5.0",

    isPro: false,
    creditCost: 0,

    isPublished: true,
    isFeatured: false,
    isSponsored: false,
    isDeleted: false,
    sponsoredBy: { name: "", url: "", logo: "" },

    isRepoTemplate: true,
    installer: {
      name: "pip",
      dependencies: "flask scikit-learn numpy pandas",
      devDependencies: "pytest black",
      installCommand: "pip install -r requirements.txt",
      addDependenciesCommand: "pip install <package>",
      addDevDependenciesCommand: "pip install <package> --dev",
    },

    folderStructureImage: "/templates/flask-ml.png",
    videoUrl: "https://youtube.com/demo23",

    views: 7200,
    copies: 180,
    downloads: 560,

    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "24",
    name: "React Native Fitness App",
    slug: "react-native-fitness-app",
    description:
      "Cross-platform fitness tracking app with React Native and Firebase.",
    stack: ["react-native", "firebase", "expo"],
    tags: ["mobile", "fitness", "cross-platform"],
    repoUrl: "https://github.com/demo/react-native-fitness",
    version: "1.1.0",

    isPro: true,
    creditCost: 7,

    isPublished: true,
    isFeatured: true,
    isSponsored: true,
    isDeleted: false,
    sponsoredBy: {
      name: "Firebase",
      url: "https://firebase.google.com",
      logo: "/logos/firebase.svg",
    },

    isRepoTemplate: true,
    installer: {
      name: "npm",
      dependencies: "react-native expo firebase",
      devDependencies: "eslint prettier jest",
      installCommand: "npm install",
      addDependenciesCommand: "npm install <package>",
      addDevDependenciesCommand: "npm install -D <package>",
    },

    folderStructureImage: "/templates/react-native-fitness.png",
    videoUrl: "https://youtube.com/demo24",

    views: 11000,
    copies: 390,
    downloads: 950,

    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "25",
    name: "Spring Boot Microservice",
    slug: "spring-boot-microservice",
    description: "Java Spring Boot microservice template with REST and Docker.",
    stack: ["spring-boot", "java", "docker"],
    tags: ["backend", "microservice", "java"],
    repoUrl: "https://github.com/demo/spring-boot-microservice",
    version: "1.0.0",

    isPro: true,
    creditCost: 12,

    isPublished: true,
    isFeatured: false,
    isSponsored: false,
    isDeleted: false,
    sponsoredBy: { name: "", url: "", logo: "" },

    isRepoTemplate: true,
    installer: {
      name: "maven",
      dependencies: "spring-boot-starter-web spring-boot-starter-data-jpa",
      devDependencies: "junit mockito",
      installCommand: "mvn install",
      addDependenciesCommand: "mvn dependency:resolve",
      addDevDependenciesCommand: "mvn dependency:resolve -Dscope=test",
    },

    folderStructureImage: "/templates/spring-boot.png",
    videoUrl: "https://youtube.com/demo25",

    views: 9500,
    copies: 260,
    downloads: 780,

    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "31",
    name: "Auth Module",
    slug: "auth-module",
    description: "Reusable authentication module with JWT and refresh tokens.",
    stack: ["nodejs", "express", "jwt"],
    tags: ["auth", "module", "security"],
    repoUrl: "https://github.com/demo/auth-module",
    version: "1.0.0",
    isPro: false,
    creditCost: 0,
    isPublished: true,
    isFeatured: false,
    isSponsored: false,
    isDeleted: false,
    sponsoredBy: { name: "", url: "", logo: "" },
    isRepoTemplate: false,
    installer: {
      name: "npm",
      dependencies: "jsonwebtoken bcrypt",
      devDependencies: "jest eslint",
      installCommand: "npm install",
      addDependenciesCommand: "npm install <package>",
      addDevDependenciesCommand: "npm install -D <package>",
    },
    folderStructureImage: "/templates/auth-module.png",
    videoUrl: "",
    views: 4200,
    copies: 800,
    downloads: 2100,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "32",
    name: "Blog CMS Repo",
    slug: "blog-cms-repo",
    description: "Full blog CMS with Next.js, Prisma, and PostgreSQL.",
    stack: ["nextjs", "prisma", "postgresql"],
    tags: ["cms", "blog", "repo"],
    repoUrl: "https://github.com/demo/blog-cms",
    version: "2.2.0",
    isPro: true,
    creditCost: 6,
    isPublished: true,
    isFeatured: true,
    isSponsored: false,
    isDeleted: false,
    sponsoredBy: { name: "", url: "", logo: "" },
    isRepoTemplate: true,
    installer: {
      name: "npm",
      dependencies: "next prisma @prisma/client",
      devDependencies: "typescript eslint",
      installCommand: "npm install",
      addDependenciesCommand: "npm install <package>",
      addDevDependenciesCommand: "npm install -D <package>",
    },
    folderStructureImage: "/templates/blog-cms.png",
    videoUrl: "https://youtube.com/demo-blog",
    views: 9800,
    copies: 2100,
    downloads: 4500,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "33",
    name: "Payments Module",
    slug: "payments-module",
    description: "Stripe payments integration module for Node.js apps.",
    stack: ["nodejs", "stripe"],
    tags: ["payments", "module", "stripe"],
    repoUrl: "https://github.com/demo/payments-module",
    version: "1.1.0",
    isPro: false,
    creditCost: 0,
    isPublished: true,
    isFeatured: false,
    isSponsored: true,
    isDeleted: false,
    sponsoredBy: {
      name: "Stripe",
      url: "https://stripe.com",
      logo: "/logos/stripe.svg",
    },
    isRepoTemplate: false,
    installer: {
      name: "npm",
      dependencies: "stripe",
      devDependencies: "jest",
      installCommand: "npm install",
      addDependenciesCommand: "npm install stripe",
      addDevDependenciesCommand: "npm install -D jest",
    },
    folderStructureImage: "/templates/payments-module.png",
    videoUrl: "",
    views: 5600,
    copies: 1200,
    downloads: 3100,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "34",
    name: "Portfolio Repo",
    slug: "portfolio-repo",
    description: "Developer portfolio starter with Next.js and Tailwind.",
    stack: ["nextjs", "tailwindcss"],
    tags: ["portfolio", "repo", "frontend"],
    repoUrl: "https://github.com/demo/portfolio-repo",
    version: "1.0.0",
    isPro: false,
    creditCost: 0,
    isPublished: true,
    isFeatured: true,
    isSponsored: false,
    isDeleted: false,
    sponsoredBy: { name: "", url: "", logo: "" },
    isRepoTemplate: true,
    installer: {
      name: "npm",
      dependencies: "next react tailwindcss",
      devDependencies: "eslint prettier",
      installCommand: "npm install",
      addDependenciesCommand: "npm install <package>",
      addDevDependenciesCommand: "npm install -D <package>",
    },
    folderStructureImage: "/templates/portfolio-repo.png",
    videoUrl: "https://youtube.com/demo-portfolio",
    views: 7200,
    copies: 1500,
    downloads: 3200,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "35",
    name: "Notifications Module",
    slug: "notifications-module",
    description: "Reusable notification system with email and SMS support.",
    stack: ["nodejs", "twilio", "nodemailer"],
    tags: ["notifications", "module", "email", "sms"],
    repoUrl: "https://github.com/demo/notifications-module",
    version: "1.0.0",
    isPro: false,
    creditCost: 0,
    isPublished: true,
    isFeatured: false,
    isSponsored: false,
    isDeleted: false,
    sponsoredBy: { name: "", url: "", logo: "" },
    isRepoTemplate: false,
    installer: {
      name: "npm",
      dependencies: "nodemailer twilio",
      devDependencies: "jest",
      installCommand: "npm install",
      addDependenciesCommand: "npm install <package>",
      addDevDependenciesCommand: "npm install -D jest",
    },
    folderStructureImage: "/templates/notifications-module.png",
    videoUrl: "",
    views: 4300,
    copies: 900,
    downloads: 2100,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "36",
    name: "Ecommerce Repo",
    slug: "ecommerce-repo",
    description: "Full ecommerce starter with cart, checkout, and Stripe.",
    stack: ["nextjs", "stripe", "tailwindcss"],
    tags: ["ecommerce", "repo", "store"],
    repoUrl: "https://github.com/demo/ecommerce-repo",
    version: "2.0.0",
    isPro: true,
    creditCost: 9,
    isPublished: true,
    isFeatured: true,
    isSponsored: false,
    isDeleted: false,
    sponsoredBy: { name: "", url: "", logo: "" },
    isRepoTemplate: true,
    installer: {
      name: "npm",
      dependencies: "stripe",
      devDependencies: "eslint",
      installCommand: "npm install",
      addDependenciesCommand: "npm install stripe",
      addDevDependenciesCommand: "npm install -D eslint",
    },
    folderStructureImage: "/templates/ecommerce-repo.png",
    videoUrl: "https://youtube.com/demo-ecommerce",
    views: 15000,
    copies: 3000,
    downloads: 7000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "37",
    name: "Analytics Module",
    slug: "analytics-module",
    description: "Drop-in analytics tracking module with Google Analytics.",
    stack: ["javascript", "google-analytics"],
    tags: ["analytics", "module", "tracking"],
    repoUrl: "https://github.com/demo/analytics-module",
    version: "1.0.0",
    isPro: false,
    creditCost: 0,
    isPublished: true,
    isFeatured: false,
    isSponsored: true,
    isDeleted: false,
    sponsoredBy: {
      name: "Google",
      url: "https://analytics.google.com",
      logo: "/logos/google.svg",
    },
    isRepoTemplate: false,
    installer: {
      name: "npm",
      dependencies: "react-ga",
      devDependencies: "eslint",
      installCommand: "npm install",
      addDependenciesCommand: "npm install react-ga",
      addDevDependenciesCommand: "npm install -D eslint",
    },
    folderStructureImage: "/templates/analytics-module.png",
    videoUrl: "",
    views: 6200,
    copies: 1100,
    downloads: 2800,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "38",
    name: "Learning LMS Repo",
    slug: "learning-lms-repo",
    description:
      "Learning management system with courses, quizzes, and progress tracking.",
    stack: ["nextjs", "postgresql", "tailwindcss"],
    tags: ["lms", "repo", "education"],
    repoUrl: "https://github.com/demo/lms-repo",
    version: "1.0.0",
    isPro: true,
    creditCost: 10,
    isPublished: true,
    isFeatured: true,
    isSponsored: false,
    isDeleted: false,
    sponsoredBy: { name: "", url: "", logo: "" },
    isRepoTemplate: true,
    installer: {
      name: "npm",
      dependencies: "pg",
      devDependencies: "eslint",
      installCommand: "npm install",
      addDependenciesCommand: "npm install pg",
      addDevDependenciesCommand: "npm install -D eslint",
    },
    folderStructureImage: "/templates/learning-lms-repo.png",
    videoUrl: "https://youtube.com/demo-learning-lms",
    views: 12000,
    copies: 2000,
    downloads: 5000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
